
DROP TABLE IF EXISTS tableCreator2;
CREATE TABLE tableCreator2 (classId INT,dia VARCHAR(3),hora INT,isFree Bit, planta INT,userID VARCHAR(20));
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (102,'MON',10,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (103,'MON',11,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (101,'MON',12,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (104,'MON',10,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (105,'MON',11,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (106,'MON',12,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (108,'MON',13,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (110,'MON',14,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (109,'MON',15,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (107,'MON',16,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (111,'MON',17,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (112,'MON',10,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (113,'MON',11,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (201,'MON',14,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (202,'MON',16,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (203,'MON',9,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (204,'MON',18,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (205,'MON',19,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (206,'MON',8,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (207,'MON',10,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (208,'MON',11,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (209,'MON',12,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (211,'MON',16,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (212,'MON',10,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (213,'MON',12,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (301,'MON',14,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (302,'MON',16,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (303,'MON',18,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (304,'MON',15,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (305,'MON',13,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (306,'MON',12,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (307,'MON',11,0,3,null);

INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (102,'SAT',12,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (103,'SAT',15,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (101,'SAT',13,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (104,'SAT',8,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (105,'SAT',9,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (106,'SAT',9,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (108,'SAT',14,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (110,'SAT',13,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (109,'SAT',15,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (107,'SAT',12,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (111,'SAT',13,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (112,'SAT',19,0,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (113,'SAT',15,1,1,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (201,'SAT',12,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (202,'SAT',11,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (203,'SAT',10,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (204,'SAT',16,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (205,'SAT',18,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (206,'SAT',10,1,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (207,'SAT',11,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (208,'SAT',14,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (209,'SAT',12,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (210,'SAT',16,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (211,'SAT',10,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (212,'SAT',11,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (213,'SAT',12,0,2,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (301,'SAT',16,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (302,'SAT',18,0,3,null);

INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (303,'SAT',15,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (304,'SAT',13,0,3,null);


INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (305,'SAT',12,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (306,'SAT',11,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (307,'SAT',10,0,3,null);

INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (306,'SAT',9,0,3,null);
INSERT INTO tableCreator2 (classId,dia,hora,isFree,planta,userID) VALUES (307,'SAT',8,0,3,null);

DROP TABLE IF EXISTS tableLogin;
CREATE TABLE tableLogin (userID VARCHAR(20) PRIMARY KEY, passwd VARCHAR(20), role VARCHAR(20));
INSERT INTO tableLogin (userID,passwd,role) VALUES ('professor','professor','Professor');
INSERT INTO tableLogin (userID,passwd,role) VALUES ('admin','admin','Administrative');
INSERT INTO tableLogin (userID,passwd,role) VALUES ('student','student','Student');